
<?php $menu = Mage::getSingleton('core/layout')
	->createBlock('wordpress/menu')
	->setMenuId(Mage::getStoreConfig('wordpress/menu/id'))
	->includeWrapper(true) // Includes the wrapping <ul tag
	->setListId('magazin-nav') ?>

<div class="page-title blog-title <?php if (!$this->isFirstPage()): ?>not-<?php endif; ?>first-page<?php if ($this->isFirstPage() && $this->getTagLine()): ?> with-tagline<?php endif; ?>">
	<h1><?php echo $this->escapeHtml($this->getBlogTitle()) ?></h1>
</div>
<?php if ($this->isFirstPage() && $this->getTagLine()): ?>
	<p class="blog-desc blog-tag-line"><?php echo $this->escapeHtml($this->getTagLine()) ?></p>
<?php endif; ?>

<?php echo $menu->toHtml() ?>

<div class="blog-home">
	<?php echo $this->getPostListHtml() ?>
</div>
